# Generated by Django 2.0.1 on 2018-02-10 15:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0004_auto_20180210_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='user_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='match_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 10, 22, 27, 34, 988538)),
        ),
    ]
