# Generated by Django 2.0.1 on 2018-02-11 06:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0005_auto_20180210_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='match_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 11, 13, 59, 49, 641806)),
        ),
        migrations.AddField(
            model_name='data',
            name='team_a',
            field=models.CharField(default='-', max_length=200),
        ),
        migrations.AddField(
            model_name='data',
            name='team_b',
            field=models.CharField(default='-', max_length=200),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='match_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 11, 13, 59, 49, 641806)),
        ),
    ]
