# Generated by Django 2.0.1 on 2018-02-11 07:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0006_auto_20180211_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='match_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='data',
            name='team_a',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='data',
            name='team_b',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='match_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 11, 14, 0, 50, 441907)),
        ),
    ]
