# Generated by Django 2.0.1 on 2018-02-11 13:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0009_auto_20180211_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='match_date',
        ),
        migrations.RemoveField(
            model_name='data',
            name='team_a',
        ),
        migrations.RemoveField(
            model_name='data',
            name='team_b',
        ),
        migrations.AlterField(
            model_name='schedule',
            name='match_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 11, 20, 8, 9, 380301)),
        ),
    ]
