# Generated by Django 2.0.1 on 2018-02-11 15:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0010_auto_20180211_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='match_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 11, 22, 8, 21, 718643)),
        ),
    ]
