# Generated by Django 2.0.1 on 2018-02-12 02:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0011_auto_20180211_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='match_point',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='match_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 12, 9, 56, 5, 925813)),
        ),
    ]
