# Generated by Django 2.0.1 on 2018-02-13 05:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0015_auto_20180212_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='predict_winner',
            field=models.CharField(choices=[(1, 'Đội A'), ('BALANCE', 'Hòa'), ('BWIN', 'Đội B'), ('-', '-')], default='-', max_length=200),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='match_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 13, 12, 45, 39, 463423)),
        ),
    ]
