# Generated by Django 2.0.1 on 2018-02-13 08:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0019_auto_20180213_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='match_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 13, 15, 16, 22, 851815)),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='score_a',
            field=models.CharField(choices=[(88, 'Chưa thi đấu'), (0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20')], default=88, max_length=200),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='score_b',
            field=models.CharField(choices=[(88, 'Chưa thi đấu'), (0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20')], default=88, max_length=200),
        ),
    ]
