# Generated by Django 2.0.1 on 2018-02-16 07:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0028_auto_20180214_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='predict_winner',
            field=models.CharField(choices=[('AWIN', 'Đội A thắng'), ('BALANCE', 'Hai đội hòa'), ('BWIN', 'Đội B thắng'), ('-', '-')], default='-', max_length=200),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='match_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 16, 14, 12, 32, 354409)),
        ),
    ]
