# Generated by Django 2.0.1 on 2018-02-16 08:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0031_auto_20180216_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='user_name',
        ),
        migrations.AlterField(
            model_name='schedule',
            name='match_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 16, 15, 10, 22, 860328)),
        ),
    ]
