# Generated by Django 2.0.1 on 2018-02-16 14:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0035_auto_20180216_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='level',
            field=models.CharField(choices=[('1-32', 'Vòng bảng'), ('1-16', 'Vòng 1-16'), ('Quarterfinal', 'Tứ kết'), ('Semifinal', 'Bán kết'), ('Third place', 'Giải ba'), ('Final', 'Chung kết')], default='1-32', max_length=200),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='match_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 16, 21, 26, 0, 934916)),
        ),
    ]
